# server {
#   listen 80;
#   # server_name social-app.jeanbeguerisse.com;
#     server_name socialapp.com;


#   root /usr/share/nginx/html;
#   index index.html;

#   # Redirige les appels API vers le backend
#   location /api/ {
#     proxy_pass http://server:8000/api/;
#     proxy_http_version 1.1;
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Proto $scheme;
#     proxy_set_header Accept-Encoding "";
#     proxy_buffering off;

#     add_header Access-Control-Allow-Origin http://socialapp.com;
#     add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE, PATCH";
#     add_header Access-Control-Allow-Headers "Authorization, Content-Type";

#     # Pour que les requêtes OPTIONS répondent
#     if ($request_method = OPTIONS) {
#       return 204;
#     }
#   }

#   # Toutes les autres requêtes vont vers le front (SPA)
#   location / {
#     try_files $uri /index.html;
#   }
# }


#Prod local nginx configuration for socialapp.com
# server {
#   listen 80;
#   server_name socialapp.com;

#   root /usr/share/nginx/html;
#   index index.html;

#   location /api/ {
#     proxy_pass http://server:8000/api/;
#     proxy_http_version 1.1;
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Proto $scheme;
#     proxy_set_header Connection "";

#     proxy_buffering off;
#     chunked_transfer_encoding off;

#     add_header Access-Control-Allow-Origin * always;
#     add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE, PATCH" always;
#     add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

#     if ($request_method = OPTIONS) {
#       add_header Content-Length 0;
#       return 204;
#     }
#   }

#   location / {
#     try_files $uri /index.html;
#   }
# }


#Prod VPS nginx configuration for social-app.jeanbeguerisse.com
server {
  listen 80;
  server_name social-app.jeanbeguerisse.com;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://server:8000/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";

    proxy_buffering off;
    chunked_transfer_encoding off;

    add_header Access-Control-Allow-Origin social-app.jeanbeguerisse.com always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE, PATCH" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

    if ($request_method = OPTIONS) {
      add_header Content-Length 0;
      return 204;
    }
  }

  location / {
    try_files $uri /index.html;
  }
}